### ISSUE TITLE
FileNotFoundError stabilityai/stable-diffusion-2-1-base and prompt not found

### ISSUE THREAD

**Issue by LucioC** [magic-research/magic-boost#8]
Hello,

I'm trying to run the refinement on instantmesh, but it seems my environment might be missing something. I'm using windows.

I first ran:
`python launch.py --gpu 0 --config './configs/mesh-fitting-instantmesh.yaml' --train tag=orc1 system.guidance.geometry.shape_init='./load/mesh_instantmesh/orc1.obj'`

This correctly generated a .ckpt file and test results.

Then the next step:
```
$env:PYTHONPATH = "${env:PYTHONPATH};./extern/MVC"
python launch.py --gpu 0 --config ./configs/refine_instantmesh.yaml --train tag=orc1 system.prompt_processor.prompt="a orc" data.mvcond_dir='./load/mv_instantmesh/orc1' data.image_path='./load/mv_instantmesh/orc1/0.png' system.weights='./outputs/mesh-fitting-nerf-instantmesh/orc1@20240620-025045/ckpts/last.ckpt'
```

This is giving me the following output error:
```
[INFO] Using view-dependent prompts [side]:[a orc, side view] [front]:[a orc, front view] [back]:[a orc, back view] [overhead]:[a orc, overhead view]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "G:\anaconda\magic-boost\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "G:\anaconda\magic-boost\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\magic-boost\threestudio\models\prompt_processors\stable_diffusion_prompt_processor.py", line 75, in spawn_func
    tokenizer = AutoTokenizer.from_pretrained(
  File "G:\anaconda\magic-boost\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 751, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "G:\anaconda\magic-boost\lib\site-packages\transformers\tokenization_utils_base.py", line 2017, in from_pretrained
    return cls._from_pretrained(
  File "G:\anaconda\magic-boost\lib\site-packages\transformers\tokenization_utils_base.py", line 2049, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "G:\anaconda\magic-boost\lib\site-packages\transformers\tokenization_utils_base.py", line 2187, in _from_pretrained
    special_tokens_map = json.load(special_tokens_map_handle)
  File "G:\anaconda\magic-boost\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "G:\anaconda\magic-boost\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "G:\anaconda\magic-boost\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "G:\anaconda\magic-boost\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\magic-boost\launch.py", line 238, in <module>
    main(args, extras)
  File "D:\magic-boost\launch.py", line 105, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "D:\magic-boost\threestudio\systems\base.py", line 41, in __init__
    self.configure()
  File "D:\magic-boost\threestudio\systems\magicboost.py", line 68, in configure
    self.prompt_processor = threestudio.find(self.cfg.prompt_processor_type)(
  File "D:\magic-boost\threestudio\utils\base.py", line 63, in __init__
    self.configure(*args, **kwargs)
  File "D:\magic-boost\threestudio\models\prompt_processors\base.py", line 340, in configure
    self.load_text_embeddings()
  File "D:\magic-boost\threestudio\models\prompt_processors\base.py", line 396, in load_text_embeddings
    self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]
  File "D:\magic-boost\threestudio\models\prompt_processors\base.py", line 414, in load_from_cache
    raise FileNotFoundError(
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings\58cd640323112eb86685021f4b99b16b.pt for model stabilityai/stable-diffusion-2-1-base and prompt [a orc] not found.
```
The mentioned .pt file is not in the expected folder. Not sure why?

**Comment by LucioC** [comment]
similar issue to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12807
I had to delete the huggingface cache folder of the stable diffusion model and download it again.

**Comment by Hualiang789** [comment]
Hello, I also come to this question. How did you specifically solve it? Do you delete prompt_library.json and download it again?

**Comment by Hualiang789** [comment]
> 稳定扩散模型的 huggingface 缓存文件夹
How did this find this cache file?
